In [ ]:
# Name: Chaithra Kopparam Cheluvaiah
# Nov 23, 2021

### Introduction to Numpy

1. NumPy is a linear algebra library for python
2. Numpy is also incredibly fast, as it has its binding to C libraries
3. It is highle recommended to install python using anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of conda install
4. if you have Anaconda, install Numpy by going to your terminal or command prompt and typing:
```conda install numpy
pip install numpy```

In [2]:
import numpy as np

In [ ]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.9/dist-packages/numpy/version.py'>

### Numpy Arrays - np.array()

1. Numpy arrays essentially come in two flavours: vectors and matrcies
2. Vectors are either 1-d Arrays or 2-d Matrices (but you should note a matrix can still have only one row or one column).

In [ ]:
#casting normal python list to a numpy array
my_list = [1,2,3,4,5,6,7,8,9,10]

In [ ]:
arr = np.array(my_list)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr.shape # (10, ) 1d array with 10 elements

(10,)

In [ ]:
# casting list of list to 2-d numpy array - matrix
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Usually, We use Numpy built-in generation methods to create arrays a lot faster and a lot simpler. 
### Most Commonly used are:

In [ ]:
# similar to python's range method
# [start, stop)
np.arange(start=0,stop=10)

# However, python range returns range object. it needs to be typecasted to list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,step=2) #step =2 , to get even numbers

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(10) # start and step are optional

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# we cannot create 2d array with np.arange()

In [ ]:
# generate arrays with all zeros
np.zeros(3) # 1-d array

array([0., 0., 0.])

In [ ]:
np.zeros((2,3)) # pass tuple for matrix with rows and cols in a tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# generate arrays with all ones
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# evenly spaced numbers over a specified interval - start and end in the interval are inclusive
# [start, stop]
np.linspace(0,5,10) # third argument: number of evenly spaced points you need

# range also provides evenly spaced values but third argumnet is step size
# (5-0)/9 should be the step size while using range

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.linspace(2,3,5) # (3-2)/4 -> each step size

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
# CREATING IDENTITY MATRIX

np.eye(4) # it is two dimensional square matrix with diagonal elements 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [1]:
c = np.full((2,4), 7.0)
print(c)

NameError: ignored

### Creating Array with Random Samples from Uniform Distribution:
Discrete Unifrom Distribtion: https://www.youtube.com/watch?v=cyIEhL92wiw
<br>Continuous Uniform Distribution: https://www.youtube.com/watch?v=j8XLYFzTJzE 

In [ ]:
# Creating matrix with random numbers

# Creates an array of the given shape and populate it with random samples from a uniform probability distribution over [0, 1).

np.random.rand(5)  # 1-d array

array([0.96732068, 0.39446933, 0.52151162, 0.53887034, 0.86505111])

In [ ]:
np.random.rand(5,5) # 2-d array; we dont pass tuple here

array([[0.51616539, 0.51411093, 0.65964424, 0.56734942, 0.11191331],
       [0.1344196 , 0.35338015, 0.13350211, 0.22951089, 0.44175426],
       [0.5565056 , 0.39924352, 0.07446543, 0.51763062, 0.38403547],
       [0.81507096, 0.62107636, 0.34159101, 0.14979491, 0.21920338],
       [0.22458068, 0.29033715, 0.42359205, 0.33535379, 0.60059061]])

In [ ]:
# Random Samples from normal distribution (bell-shaped) centered around 0 or gaussian distribution
np.random.randn(5)

array([-0.04019641,  0.54094123,  0.82284252,  1.65728511, -2.34513282])

In [ ]:
np.random.randn(4,4) # 2-d array; we dont pass tuple here

array([[ 1.31750278,  0.26619713,  0.06743921, -0.53706243],
       [-0.65809724,  0.98242562,  0.18558572, -0.21871993],
       [-0.51151392,  0.57274669,  0.84185018,  1.04220552],
       [-1.66090854, -1.41703544,  0.54552068, -0.12959991]])

In [ ]:
# random integer between low to high value
np.random.randint(1,100) # 1- inclusive, 100-exclusive

7

In [ ]:
np.random.randint(1,100, 10)  # third arg - number of random integers we want

array([82,  6, 78, 45, 51, 21,  3, 58, 38, 27])

### Attributes and Methods of an Array

In [ ]:
arr = np.arange(16)

In [ ]:
arr # 1-dimensional array of 0 upto 24 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
ran_arr = np.random.randint(0,50, 10)

In [ ]:
ran_arr

array([35, 11, 20,  1, 30, 10, 19, 43, 18, 14])

In [ ]:
# RESHAPE METHOD - returns the same data but in new shape

# it useful for converting 1d array produced from methods like np.arange(), np.linspace() which does not have functionality to 
# produce 2d arrays

arr.reshape(4,4) # pass the new dimensions we want

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr.reshape(8,2) 

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
arr.reshape(16,1) 

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [ ]:
arr.reshape(1,16)  # notice that it is 2d array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
# we might get an error if we cannot fill up that matrix completely

arr.reshape(5,10)

ValueError: cannot reshape array of size 16 into shape (5,10)

In [ ]:
arr.reshape(2,3)

ValueError: cannot reshape array of size 16 into shape (2,3)

In [ ]:
# rows * columns = number of elements in the array

In [ ]:
# MAX VALUE
ran_arr.max()

44

In [ ]:
ran_arr.min()

8

In [ ]:
arr.max() # works even for 2-dimensional arrays

15

In [ ]:
# GETTING MIN INDEX & MAX INDEX
ran_arr.argmax()  

1

In [ ]:
arr = arr.reshape(5,5)

ValueError: cannot reshape array of size 16 into shape (5,5)

In [ ]:
arr.argmax() # By default, the index is into the flattened array, otherwise along the specified axis.

15

In [ ]:
# SHAPE

arr.shape

(16,)

In [ ]:
ran_arr.shape  # indicates its 1-dimensional array

(10,)

In [ ]:
arr.dtype  # data type in the array

dtype('int32')

### QUICK REVIEW

1. Create numpy arrays:
    - Casting a list - `np.array()`
    - Built-in functions - `np.arange()`, `np.zeros()`, `np.ones()`, `np.linspace()`, `np.eye()`
    - Random generation functions - `np.random.rand()`, `np.random.randn()`, `np.random.randint()`
2. Methods: `arr.reshape()`, `arr.min()`, `arr.max()`, `arr.argmin()`, `arr.argmax()`, `arr.shape`, `arr.dtype`