# Numpy Array Indexing and Selection
- slicing
- broadcasting
- shallow copy and deep copy
- 1d array conditional selection
- indexing 2d array
- slicing 2d array
- fancy indexing

In [2]:
# Name: Chaithra Kopparam Cheluvaiah
# Nov 24, 2021

In [3]:
import numpy as np

In [15]:
range_arr = list(range(0,10)) # requires type casting to list

In [16]:
range_arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
range_arr[0:5] = 100  # cannot boradcast

TypeError: can only assign an iterable

### BRACKETS AND SLICING

In [4]:
# creating sample array
arr = np.arange(11) # does not require type casting unlike range
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8] # to get single value; just like python list

8

In [6]:
arr[9] = 90 # mutable
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 90, 10])

In [22]:
arr[1:5] # slicing similar to python

array([1, 2, 3, 4])

In [23]:
arr[:5] # removing start point

array([0, 1, 2, 3, 4])

In [24]:
arr[:] # everything

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### BROADCASTING

In [25]:
arr[1:5] = 100 # not possible with python slicing

In [26]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### SHALLOW & DEEP COPY OF ARRAYS

In [28]:
arr_copy = arr[0:6]
arr_copy

array([  0, 100, 100, 100, 100,   5])

In [29]:
arr_copy[:] = 99 # broadcasting

In [31]:
arr_copy

array([99, 99, 99, 99, 99, 99])

In [83]:
arr # original array is also updated

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# arr_copy is a reference to original array

Data is not copied, it's a view of the original array! This avoids memory problems!

In [34]:
deep_copy = arr.copy()

In [36]:
deep_copy[:] = 100

In [37]:
deep_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [38]:
arr # remains unaffected

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### INDEXING 2D ARRAY / MATRIX

In [41]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
# double bracket format
arr_2d[2][1] # lets grab 40

40

In [49]:
# single bracket format - recommended
arr_2d[2,1]

40

In [51]:
# lets grab 30
arr_2d[1,2]

30

In [55]:
# slicing - getting top-right corner 10,15,25,30
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
arr_2d[:2] # gets only the rows

array([[ 5, 10, 15],
       [20, 25, 30]])

In [63]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
# more examples

In [67]:
sample_array = np.arange(50)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [71]:
sample_array = sample_array.reshape(5,10) # 5 rows and 10 columns
sample_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [73]:
# lets get 13,14,23,24
sample_array[1:3] # only rows are selected

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [74]:
sample_array[1:3,3:5]

array([[13, 14],
       [23, 24]])

### CONDITIONAL SELECTION

In [75]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [79]:
bool_arr = arr < 5
bool_arr

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [80]:
arr[bool_arr]

array([1, 2, 3, 4])

In [81]:
arr[arr>6]

array([ 7,  8,  9, 10])

### FANCY INDEXING

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [84]:
# sample array
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [85]:
# length of the array; number of rows
rows = arr2d.shape[0]

In [86]:
# setting up the array
for row in range(rows):
    arr2d[row] = row

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy Indexing - Use double brackets

In [87]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [89]:
# allows in any order
arr2d[[6,2,3,7,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])