In [ ]:
#Name: Chaithra Kopparam Cheluvaiah
# Nov 24, 2021

### NUMPY OPERATIONS
- **Array with Array**
- **Array with Scalars** : Broadcasting
- 0/0 is nan
- 1/0 is inf
- **Universal Array Functions** `np.sqrt(), np.exp(), np.sin(), np.min(), np.max(), np.sum(), np.log()`

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11) # 11 digits from 0-10
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Array with Array
arr + arr # adding two arrays element by element basis

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
# Array with Scalar
# numpy boradcasts the scalar to every element in the array so that operation also occurs element by element
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [ ]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

### DIVISION BY ZERO IN NUMPY

In [ ]:
1/0  # gives Error:ZeroDivisionError but not in numpy

ZeroDivisionError: division by zero

In [ ]:
arr/arr # first element is 0/0

C:\Users\Chaithra\AppData\Local\Temp/ipykernel_38580/4159632396.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr # first element is 0/0


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

It executed and returned nan/null value. It does not throw error!!

In [ ]:
1/arr # 1/0 instad of 0/0

C:\Users\Chaithra\AppData\Local\Temp/ipykernel_38580/1734033717.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr # 1/0 instad of 0/0


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In this case also we get warning but in we get infinity instead of nan

In [ ]:
# Universal Array Functions - which are just mathematical operations and broadcast across entire array

# take square root of every element in the array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.exp(arr)  # exponential function is e^x

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
np.max(arr)

10

In [ ]:
# same as array.max()
arr.max()

10

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.log(arr) # natural logarithm ln(x)

C:\Users\Chaithra\AppData\Local\Temp/ipykernel_38580/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

Notice the warning from Numpy. `ln(0)=-ထ`. 

Universal Array Functions Reference: https://numpy.org/doc/stable/reference/ufuncs.html